MAnggiarMustofa/GI-Download-Library

GenshinImpact_Beta/2.5.5x.md, GenshinImpact_Beta/2.6.5x.md, GenshinImpact_Beta/3.0.5x.md
Update 2554,3052 full packge
Update 2554,2654,3053 upgradge package
=> update more links

GenshinImpact/Audio/2.3.0.md, GenshinImpact/Audio/2.4.0.md, GenshinImpact/Audio/2.5.0.md, GenshinImpact/Client/2.3.0.md, GenshinImpact/Client/2.4.0.md, GenshinImpact/Client/2.5.0.md, GenshinImpact/Client/2.6.0.md, GenshinImpact/Client/3.0.0.md
update 2.3.0-2.5.0 os client and audio
=> update 2.3-2.5 global links

GenshinImpact_Beta/3.0.5x.md, Yuanshen_Beta/3.0.5x.md
Updated Yuanshen_Beta - GenshinImpact_Beta's 3.0.5 full client
=> Update 3.0.5 full client

GenshinImpact_Beta/2.4.5x.md, GenshinImpact_Beta/destincy.md
Updated some 245x lancher links.
更新了一些245x启动器链接
Updated a download link named destincy.
更新了一个早期名为destincy 的下载链接
=> update some old version client & lancher

GenshinImpact/Audio/3.1.0.md, GenshinImpact/Client/3.1.0.md, Yuanshen/Audio/3.0.0.md, Yuanshen/Audio/3.1.0.md, Yuanshen/Client/3.0.0.md, Yuanshen/Client/3.1.0.md, Yuanshen_Beta/beta_launcher.md
Updated 3.0.0&3.1.0 game&audio links.
更新了3.0.0和3.1.0的语音包和本体链接
Updated final beta test lancher link
更新了三测启动器
=> Updated 3.0.0&3.1.0 game&audio and final beta test lancher links.

GenshinImpact_Beta/3.1.5x.md
By the way, do you have any contact information to contact you? For example, dc tg QQ is better than QQ（
=> Update 3.1.50 download method

Yuanshen_Beta/1.1.5x.md
=> add 1.2DEV client

GenshinImpact_Beta/1.0.x.md, GenshinImpact_Beta/1.1.x.md, GenshinImpact_Beta/1.5.5x.md, GenshinImpact_Beta/2.3.5x.md, GenshinImpact_Beta/2.5.5x.md, GenshinImpact_Beta/2.7.5x.md, Yuanshen_Beta/0.9.x.md, Yuanshen_Beta/1.0.x.md, Yuanshen_Beta/1.3.5x.md, Yuanshen_Beta/2.3.5x.md, Yuanshen_Beta/2.4.5x.md, Yuanshen_Beta/2.7.5x.md
Some links from my archive that weren't already in this repository.
Commit names explicitely tell which links have been added.
=> Additional beta links [Global+CN]

GenshinImpact_Beta/3.1.5x.md
=> add 3154 client & diff

Yuanshen_Beta/1.1.5x.md
It's been fixed here :
https://github.com/kyou-nase/GI-Download-Library/pull/18
Also this link is here:
https://github.com/kyou-nase/GI-Download-Library/blob/main/Yuanshen_Beta/1.5.5x.md
=> 1.1.54 is actually 1.5.54

Yuanshen/Audio/1.5.54.md, Yuanshen/Audio/1.6.0.md, Yuanshen/Audio/2.0.0.md, Yuanshen/Audio/2.4.0.md
It's looks same as OS audio, also i noticed that beta audio exist on mhy servers for no reason...
=> Some Audio for CN

GenshinImpact/Audio/3.2.0.md, GenshinImpact/Client/3.2.0.md, Yuanshen/Audio/3.2.0.md, Yuanshen/Client/3.2.0.md
add 320 cn and os client & diff
=> 320 update

GenshinImpact_Beta/3.2.5x.md, README.md, README_zh-CN.md
=> Add 3.2.5X and link

GenshinImpact_Beta/1.5.5x.md
link duplicated hdiff 1.4.53 1.4.54 form
https://github.com/kyou-nase/GI-Download-Library/blob/main/GenshinImpact_Beta/1.4.x.md
=> duplicate link removed

GenshinImpact/Audio/3.5.0.md, Yuanshen/Audio/3.4.0.md, Yuanshen/Audio/3.5.0.md, Yuanshen/Client/3.5.0.md
* Add 3.4 OS Audio
* Add 3.4&3.5 CN Audio&Game
=> Add New Stable Version

GenshinImpact/Audio/3.6.0.md, GenshinImpact/Client/3.6.0.md, GenshinImpact/EpicGamesSDK.md, Yuanshen/Audio/3.6.0.md, Yuanshen/BilibiliSDK.md, Yuanshen/Client/3.6.0.md
the location of sdk docs might not be quite right...?
=> Update 3.6.0 & Added SDKs

GenshinImpact/Audio/3.7.0.md, GenshinImpact/Audio/3.8.0.md, GenshinImpact/Client/3.7.0.md, GenshinImpact/Client/3.8.0.md, GenshinImpact/Client/Latest.md, Yuanshen/Audio/3.7.0.md, Yuanshen/Audio/3.8.0.md, Yuanshen/Client/3.6.0.md, Yuanshen/Client/3.7.0.md, Yuanshen/Client/3.8.0.md, Yuanshen/Client/Latest.md
Missing 3.8 Android and Cloud, I'll add these later i_i
=> Update 3.8.0 & Fix a BUNCH of errors

Yuanshen/Client/3.7.0.md, Yuanshen/Client/3.8.0.md
sorry my bad, i should have created the last pr as a draft... :(
=> 3.8 CN Android, Cloud

GenshinImpact/Client/1.0.0.md
randomly found this in a old install of genshin kek
=> add 1.0.0 to 1.0.1 diff

GenshinImpact/Client/4.1.0.md, Yuanshen/Client/4.1.0.md
Update available 4.1.0 URLs
Original 4.1.0 URL is not available
=> Updata 4.1.0 Urls
